In [1]:
import numpy as np

In [2]:
#array unidimensional
arr = np.arange(1, 11, dtype=int)

In [3]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# Indexação de arrays unidimensionais


In [5]:
arr[4]

5

In [6]:
arr[2:4]

array([3, 4])

In [7]:
arr[2:5]

array([3, 4, 5])

In [8]:
arr[:5]

array([1, 2, 3, 4, 5])

In [9]:
arr[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [10]:
# Indexação de arrays bidimensionais

In [12]:
arr2 = np.random.randint(10,50,size=(3,3))

In [13]:
arr2

array([[33, 11, 20],
       [38, 36, 20],
       [25, 37, 15]])

In [14]:
arr2[1][1]

36

In [15]:
arr2[2][2]

15

In [16]:
arr2[2][0:2]

array([25, 37])

In [19]:
arr3 = np.random.randint(1, 101,size=(10,10))

In [20]:
arr3

array([[54, 11, 50, 59,  1, 18, 52, 56, 94, 22],
       [49, 62, 23, 75,  8, 72, 60, 83, 75, 70],
       [ 2, 33, 92, 50, 23,  2, 51, 89,  6, 51],
       [11, 91,  2,  3, 54, 88, 77, 30, 87, 11],
       [84, 72, 29, 15, 66, 33, 92, 92, 82, 53],
       [61, 27, 98,  9, 18, 84, 39, 48, 36, 76],
       [ 3, 90, 69, 48,  5, 73, 47, 40,  5, 33],
       [ 3, 41, 56, 37, 65, 44, 80, 34, 97, 18],
       [81, 38, 85, 38, 69, 11, 42, 34, 51, 53],
       [73, 45, 32, 25, 80, 64, 35, 24, 41, 82]])

In [21]:
arr3[3][:]

array([11, 91,  2,  3, 54, 88, 77, 30, 87, 11])

In [25]:
arr3[4:7][:]

array([[84, 72, 29, 15, 66, 33, 92, 92, 82, 53],
       [61, 27, 98,  9, 18, 84, 39, 48, 36, 76],
       [ 3, 90, 69, 48,  5, 73, 47, 40,  5, 33]])

In [28]:
arr3[6:7,5:8]

array([[73, 47, 40]])

In [31]:
# array[linhas,colunas]
arr3[6:8,0:5]

array([[ 3, 90, 69, 48,  5],
       [ 3, 41, 56, 37, 65]])

In [32]:
#colunas.index = 0, 1, 2, 3, 4
#linhas.index = 6, 7